### PR TITLE
data binding fix

### PR DESCRIPTION
**Pull request by denm80**
Data binding works incorrectly.

For example, if I change demo in such way:

```
<template id="t" is="dom-bind"  test-data="test-value">
...
<lazy-pages selected="{{selected}}">

    <template is="dom-if" restamp>
      <link rel="import" href="../bower_components/paper-input/paper-input.html">
      <div style="background-color: #EEE">
        <p>Page One is inside a dom-if</p>
        <paper-input value="{{test-data}}"></paper-input>
      </div>
    </template>
...
</lazy-pages>
...
```

Data binding will not work at all.

I fixed it. Should use "Polymer.Base.importHref" before "template.if = true". 
Also curently I didn't found any problem with IE.

### CODE REVIEW

**Comment by denm80** [comment]
Please ignore my two last commits.

**Comment by atotic** [comment]
This does not look like a data binding, it looks like you are trying to reimplement lazy loading.

My plan is not to do this, My simple hack did not work, and Polymer core team is working on a better thought-out solution.

I've seen other people work on this for bigger projects, and I liked their architecture better:
- preprocess and generate mapping of element-name -> file
- use this mapping inside template-if to automatically load definitions for any elements that have not been upgraded.

After seeing their work, my importHref system felt primitive, and error prone. I think the other solution is better.

So I will not take this fix. 

Question: why did you remove overflow:hidden from lazy-pages?

**Comment by denm80** [comment]
> Question: why did you remove overflow:hidden from lazy-pages?

Reason of this - incorrect work with paper-header-panel. This is just hot-fix for my test project. But I don't understand why you use so many styles for such simple template: 

```
  <template>
    <content></content>
  </template>
```

This component has to help with lazy loading only and does not have to interfere in layout. Good example is iron-pages.

> I've seen other people work on this for bigger projects, and I liked their architecture better

Could you give me links on repositories with other solutions?

> My plan is not to do this, My simple hack did not work, and Polymer core team is working on a better thought-out solution.

I would like to see solution in core of Polymer. But when will it happen? For my opinion, code like this looks very good and natural. This is flexibly, modularly and conveniently. But it doesn't work. :(

```
<template is="dom-bind" data="test">
    <template route="page-1" is="dom-if" if="expression">
        <link rel="import" href="/bower_components/paper-input/paper-input.html" />
        <paper-input value="{{data}}"></paper-input>
    </template>
....
</template>
```

If only the core of polymer had provided correct processing of it.

**Comment by atotic** [comment]
> Reason of this - incorrect work with paper-header-panel. This is just hot-fix for my test project. But I
> don't understand why you use so many styles for such simple template: 

It was some Safari bug I had to work around....

> Could you give me links on repositories with other solutions?

Unfortunately, he did not give me the code, just explained how it worked.

> I would like to see solution in core of Polymer. But when will it happen? For my opinion, code like this 
> looks very good and natural. This is flexibly, modularly and conveniently. But it doesn't work. :(

I agree with you that it looks very natural. Even more natural is not having the import link at all, that's why I liked the preprocess solution.

For now, just use your branch of lazy-pages. If the official lazy-loading solution does not happen, we might revisit.

**Pull request closed without merging**
